Added support for M5Core2 in Graphics Primitives
nanoframework/Samples pull request #302
Opened 2023-05-21 10:11 UTC by jsuutari

## Description
Added support for M5Core2 in Graphics Primitives Sample

## Motivation and Context

- Helps users with M5Core2 to run Primitives sample with minimal changes 

## How Has This Been Tested?

## Screenshots

## Types of changes

- [x] Improvement (non-breaking change that improves a sample)
- [ ] Bug fix (fixes an issue with a current sample)
- [ ] New Sample (adds a new sample)
- [ ] Config and build (change in the configuration and build system, has no impact on code or features)

## Checklist:

- [x] My code follows the code style of this project.
- [ ] My change requires a change to the documentation.
- [ ] I have updated the documentation accordingly.
- [x] I have read the **CONTRIBUTING** document.
- [ ] I have added tests to cover my changes.
- [ ] All new and existing tests passed.

2023-05-22 06:41 UTC, Ellerbach requested changes
Thanks for the proposition but this sample should work for all kind of MCU. So if you want to create a specific version for M5Stack, I'm fine. In that case, create another project, reuse all the cs file (by reference in the project, not by copy/paste), and adjust as well the README and category.txt so we're clear that it's a specific sample for M5Stack

2023-11-08 07:00 UTC, josesimoes commented
@Ellerbach this seems to be stalled... do we want to merge it anyways and rework it later?

2023-11-08 07:47 UTC, Ellerbach commented
> do we want to merge it anyways and rework it later?

No merge for this one. Like we did for others, it's ok to create 2 projects so they work directly.

2025-02-13 18:44 UTC, Ellerbach commented
@jsuutari I'll close this PR open for more than a year. If you are still willing to contribute to this sample, please create a separate project just for the M5Core2. Thanks!

2025-02-13 18:44 UTC, closed without merging