Neopixel Led Strip example added for ESP32
nanoframework/Samples pull request #41
Opened 2021-02-05 00:43 UTC by A13xs

New samples for ESP32 RTM

## Description
Added two new solutions
* NeoPixelStrip
* NeoPixelStripLowMemory

## Motivation and Context
New example of using the RMT library

## Types of changes
- [ ] Improvement (non-breaking change that improves a sample)
- [ ] Bug fix (fixes an issue with a current sample)
- [x ] New Sample (adds a new sample)

## Checklist:
- [ ] My code follows the code style of this project.
- [ ] My change requires a change to the documentation.
- [ ] I have updated the documentation accordingly.
- [ ] I have read the **CONTRIBUTING** document.
- [ ] I have added tests to cover my changes.
- [ ] All new and existing tests passed.

Signed-off-by: A13xs

2021-02-05 00:43 UTC, dnfadmin commented
[![CLA assistant check](https://cla.dotnetfoundation.org/pull/badge/not_signed)](https://cla.dotnetfoundation.org/nanoframework/Samples?pullRequest=41) <br/>Thank you for your submission, we really appreciate it. Like many open source projects, we ask that you sign our [Contributor License Agreement](https://cla.dotnetfoundation.org/nanoframework/Samples?pullRequest=41) before we can accept your contribution.<br/><br/>:x: A13xs [sign now](https://cla.dotnetfoundation.org/nanoframework/Samples?pullRequest=41)<br/><sub>You have signed the CLA already but the status is still pending? Let us [recheck](https://cla.dotnetfoundation.org/check/nanoframework/Samples?pullRequest=41) it.</sub>

2021-02-05 00:51 UTC, josesimoes requested changes
Thanks for adding these.
Please address my review comments.
Also add an entry for these on the main README (both EN and CN versions please). 😁

2021-02-05 00:51 UTC, josesimoes commented on samples/Hardware.Esp32.Rmt/NeoPixelStrip/NeoPixel/app.config
> +﻿<?xml version="1.0" encoding="utf-8"?>
The app.config file shouldn't be here. It's added by VS on occasions and has to be deleted.

2021-02-05 00:51 UTC, josesimoes commented on samples/Hardware.Esp32.Rmt/NeoPixelStripLowMemory/NeoPixel/app.config
> +﻿<?xml version="1.0" encoding="utf-8"?>
The app.config file shouldn't be here. It's added by VS on occasions and has to be deleted.

2021-02-05 18:04 UTC, A13xs commented
I removed the app.config

Global readme already has a link called "RTM interface" to the path Hardware.Esp32.Rmt

2021-02-06 09:18 UTC, josesimoes commented
> Global readme already has a link called "RTM interface" to the path Hardware.Esp32.Rmt

You are correct, of course! I missed that in the rush...

2021-02-06 09:19 UTC, josesimoes approved these changes
Thanks for adding these! Any chance you can submit a project with this in Hackster.io? 😉

2021-02-06 09:19 UTC, merged

2021-02-06 09:25 UTC, josesimoes commented
@A13xs are you on our Discord community? If yes, can you please ping me so I can properly credit your contribution?